{"content": {"suites": {"0": {"status": {"total_pass": 0, "total_skip": 0, "total_xpass": 0, "total_xfail": 0, "total_rerun": 0, "total_fail": 12, "total_error": 0}, "tests": {"0": {"status": "FAIL", "message": "AssertionError: assert 'Role with th...the database.' == 'Company with...the database.'\n  - Company with the provided ID is not found in the database.\n  ? ^ ^^^^^\n  + Role with the provided ID is not found in the database.\n  ? ^ ^^\n", "test_name": "test_create_usercompanyrole_with_invalid_company_id[3-Project-Management-21]", "rerun": "0"}, "1": {"status": "FAIL", "message": "AssertionError: assert 'Role with th...the database.' == 'Company with...the database.'\n  - Company with the provided ID is not found in the database.\n  ? ^ ^^^^^\n  + Role with the provided ID is not found in the database.\n  ? ^ ^^\n", "test_name": "test_create_usercompanyrole_with_invalid_company_id[3-Project-Management-14]", "rerun": "0"}, "2": {"status": "FAIL", "message": "AssertionError: assert 'Role with th...the database.' == 'Company with...the database.'\n  - Company with the provided ID is not found in the database.\n  ? ^ ^^^^^\n  + Role with the provided ID is not found in the database.\n  ? ^ ^^\n", "test_name": "test_create_usercompanyrole_with_invalid_company_id[3-Company-Management-31]", "rerun": "0"}, "3": {"status": "FAIL", "message": "AssertionError: assert 'Role with th...the database.' == 'Company with...the database.'\n  - Company with the provided ID is not found in the database.\n  ? ^ ^^^^^\n  + Role with the provided ID is not found in the database.\n  ? ^ ^^\n", "test_name": "test_create_usercompanyrole_with_invalid_company_id[4-Company-Management-12]", "rerun": "0"}, "4": {"status": "FAIL", "message": "AssertionError: assert 'Role with th...the database.' == 'Company with...the database.'\n  - Company with the provided ID is not found in the database.\n  ? ^ ^^^^^\n  + Role with the provided ID is not found in the database.\n  ? ^ ^^\n", "test_name": "test_create_usercompanyrole_with_invalid_company_id[4-Project-Management-33]", "rerun": "0"}, "5": {"status": "FAIL", "message": "AssertionError: assert 'Role with th...the database.' == 'Company with...the database.'\n  - Company with the provided ID is not found in the database.\n  ? ^ ^^^^^\n  + Role with the provided ID is not found in the database.\n  ? ^ ^^\n", "test_name": "test_create_usercompanyrole_with_invalid_company_id[4-Project-Management-44]", "rerun": "0"}, "6": {"status": "FAIL", "message": "AssertionError: assert 'Role with th...the database.' == 'Company with...the database.'\n  - Company with the provided ID is not found in the database.\n  ? ^ ^^^^^\n  + Role with the provided ID is not found in the database.\n  ? ^ ^^\n", "test_name": "test_create_usercompanyrole_with_invalid_company_id[5-Project-Management-23]", "rerun": "0"}, "7": {"status": "FAIL", "message": "AssertionError: assert 'Role with th...the database.' == 'Company with...the database.'\n  - Company with the provided ID is not found in the database.\n  ? ^ ^^^^^\n  + Role with the provided ID is not found in the database.\n  ? ^ ^^\n", "test_name": "test_create_usercompanyrole_with_invalid_company_id[5-Company-Management-24]", "rerun": "0"}, "8": {"status": "FAIL", "message": "AssertionError: assert 'Role with th...the database.' == 'Company with...the database.'\n  - Company with the provided ID is not found in the database.\n  ? ^ ^^^^^\n  + Role with the provided ID is not found in the database.\n  ? ^ ^^\n", "test_name": "test_create_usercompanyrole_with_invalid_company_id[5-Company-Management-33]", "rerun": "0"}, "9": {"status": "FAIL", "message": "AssertionError: assert 'Role with th...the database.' == 'Company with...the database.'\n  - Company with the provided ID is not found in the database.\n  ? ^ ^^^^^\n  + Role with the provided ID is not found in the database.\n  ? ^ ^^\n", "test_name": "test_create_usercompanyrole_with_invalid_company_id[2-Company-Management-6]", "rerun": "0"}, "10": {"status": "FAIL", "message": "AssertionError: assert 'Role with th...the database.' == 'Company with...the database.'\n  - Company with the provided ID is not found in the database.\n  ? ^ ^^^^^\n  + Role with the provided ID is not found in the database.\n  ? ^ ^^\n", "test_name": "test_create_usercompanyrole_with_invalid_company_id[6-Project-Management-36]", "rerun": "0"}, "11": {"status": "FAIL", "message": "AssertionError: assert 'Role with th...the database.' == 'Company with...the database.'\n  - Company with the provided ID is not found in the database.\n  ? ^ ^^^^^\n  + Role with the provided ID is not found in the database.\n  ? ^ ^^\n", "test_name": "test_create_usercompanyrole_with_invalid_company_id[6-Company-Management-46]", "rerun": "0"}}, "suite_name": "organization/Test_organization/test_views.py"}}}, "date": "August 26, 2021", "start_time": 1629992135.4030473, "total_suite": 1, "status": "FAIL", "status_list": {"pass": "0", "fail": "12", "skip": "0", "error": "0", "xpass": "0", "xfail": "0", "rerun": "0"}, "total_tests": "12"}