{"content": {"suites": {"0": {"status": {"total_pass": 0, "total_skip": 0, "total_xpass": 0, "total_xfail": 0, "total_rerun": 0, "total_fail": 8, "total_error": 0}, "tests": {"0": {"status": "FAIL", "message": " AssertionError: assert 'Multiple inv...fter sometime' == 'The username...s not correct'\n   - The username or password is not correct\n   + Multiple invalid password attempts. Please try after sometime\n", "test_name": "test_login_with_attempt_pass_update[testuser1@kpmg.com-Password@1234]", "rerun": "0"}, "1": {"status": "FAIL", "message": " AssertionError: assert 'Multiple inv...fter sometime' == 'The username...s not correct'\n   - The username or password is not correct\n   + Multiple invalid password attempts. Please try after sometime\n", "test_name": "test_login_with_attempt_pass_update[testuser2@kpmg.com-Password@1234]", "rerun": "0"}, "2": {"status": "FAIL", "message": " AssertionError: assert 'Multiple inv...fter sometime' == 'The username...s not correct'\n   - The username or password is not correct\n   + Multiple invalid password attempts. Please try after sometime\n", "test_name": "test_login_with_attempt_pass_update[testuser3@kpmg.com-Password@1234]", "rerun": "0"}, "3": {"status": "FAIL", "message": " AssertionError: assert 'Multiple inv...fter sometime' == 'The username...s not correct'\n   - The username or password is not correct\n   + Multiple invalid password attempts. Please try after sometime\n", "test_name": "test_login_with_attempt_pass_update[testuser4@kpmg.com-Password@1234]", "rerun": "0"}, "4": {"status": "FAIL", "message": " AssertionError: assert 'Multiple inv...fter sometime' == 'The username...s not correct'\n   - The username or password is not correct\n   + Multiple invalid password attempts. Please try after sometime\n", "test_name": "test_login_with_attempt_pass_update[testuser5@kpmg.com-Password@1234]", "rerun": "0"}, "5": {"status": "FAIL", "message": " AssertionError: assert 'Multiple inv...fter sometime' == 'The username...s not correct'\n   - The username or password is not correct\n   + Multiple invalid password attempts. Please try after sometime\n", "test_name": "test_login_with_attempt_pass_update[testuser6@kpmg.com-Password@1234]", "rerun": "0"}, "6": {"status": "FAIL", "message": " AssertionError: assert 'Multiple inv...fter sometime' == 'The username...s not correct'\n   - The username or password is not correct\n   + Multiple invalid password attempts. Please try after sometime\n", "test_name": "test_login_with_attempt_pass_update[testuser7@kpmg.com-Password@1234]", "rerun": "0"}, "7": {"status": "FAIL", "message": " AssertionError: assert 'Multiple inv...fter sometime' == 'The username...s not correct'\n   - The username or password is not correct\n   + Multiple invalid password attempts. Please try after sometime\n", "test_name": "test_login_with_attempt_pass_update[testuser8@kpmg.com-Password@1234]", "rerun": "0"}}, "suite_name": "usermanagement/Test_usermanagement/test_views.py"}}}, "date": "August 18, 2021", "start_time": 1629299443.3245652, "total_suite": 1, "status": "FAIL", "status_list": {"pass": "0", "fail": "8", "skip": "0", "error": "0", "xpass": "0", "xfail": "0", "rerun": "0"}, "total_tests": "8"}